name: Actualizar Lista IPTV

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Esta configuración aplica a todo el proceso
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  PAIS_FILTRO: "Spain"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Instalar dependencias
        run: pip install -r requirements.txt
        
      - name: Ejecutar script
        run: python src/smart_manager.py