name: Actualizar Lista IPTV
on:
  schedule:
    - cron: '0 8 * * *' # Esto significa: Ejecutar todos los días a las 08:00
  workflow_dispatch: # Esto permite que le des a un botón para ejecutarlo cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install -r requirements.txt

      - name: Ejecutar el script
        run: python src/smart_manager.py

      - name: Guardar cambios
        run: |
          git config --global user.name "Robot"
          git config --global user.email "robot@email.com"
          git add output/lista_inteligente.m3u
          git commit -m "Actualización automática de canales"
          git push